name: ci

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - '**'

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - run: uv sync --locked
      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run ty check

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - run: uv sync --locked
      - run: uv run pytest
